# Generated by Django 4.1.3 on 2022-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
